### ISSUE TITLE
sqlite3.ProgrammingError

### ISSUE THREAD

**Issue by farnulfo** [ankurd1/mdb#28]
When selecting a windows directory, I've got this error:

Traceback (most recent call last):
  File "MDB\gui.pyc", line 159, in open_folder
  File "MDB\gui.pyc", line 311, in process_dir
  File "MDB\DBbuilder.pyc", line 170, in is_in_db
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

**Comment by ankurd1** [comment]
This probably has nothing to with the location being a "share directory". The name of some particular movie file might contain unsupported characters. Can you share the name of the movie file which leads to this error?

**Comment by farnulfo** [comment]
Yes, nothing to do with the location, I've updated the title of the issue.
Don't know which file (over hundred) leads to this error (may be the name could be added to the log).
But I'm french and I have some movies with accentued letter like é or è.

**Comment by ankurd1** [comment]
Yeah. That's the issue most probably. I will fix all the db queries to use unicode. That should solve your issue!

**Comment by farnulfo** [comment]
Thanks for your fast answer !

PS.: Sorry, I've clicked the wrong button (Close Issue)
